/* *************************
    *** USER SIGNUP ***
************************** */
//This function will fetch information from our user/create endpoint on the server (http://localhost:3000/user/create) and handle that information by chaining promises together.
function userSignUp() {
 //console.log('userSignUp Function Called')
    let userEmail = document.getElementById('emailSignup').value;
    let userPass = document.getElementById('pwdSignup').value;
    let newUserData = { user: { email: userEmail, password: userPass } };
    console.log(`NEWUSERDATA ==> ${newUserData.user.email} ${newUserData.user.password}`); //email and password entered into sign up fields)

    fetch('http://localhost:3000/user/create', { //fetching from the user create endpoint created in the server
        method: 'POST', //route in the server handles a POST request so our method is a POST. THESE TWO MUST MATCH
        //If a route takes a POST request, then the declared method in the request should be POST. 
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(newUserData) //newUserData is turned into a JSON string.

    })
    .then(response => response.json()) //parses response into JSON
    .then((response) => {
        console.log(response.sessionToken); //logging sessionToken
        let token = response.sessionToken; //creating variable token
        localStorage.setItem('SessionToken', token); //access the localStorage for the current domain we are using and -
        //use the  setItem method to set the SessionToken in local storage to be the token generated by our server.
        tokenChecker() //calling the tokenChecker function
    })
    .catch((err) => {
        console.log(err);
    })
}


/* *************************
    *** USER LOGIN ***
************************** */
function userLogin() {
 console.log('userLogin Function Called')
}


/* *************************
    *** USER LOGOUT ***
************************** */
function userLogout() {
 console.log('userLogout Function Called')
}


/* *************************
*** TOKEN CHECKER FUNCTION ***
************************** */
function tokenChecker() {
 console.log('tokenChecker Function Called')
}
tokenChecker()